## Importação de Pacotes

In [141]:
import pandas as pd
import re

## Contato Inicial

### Informações sobre as Características
titulo - nome do livro

codigo_titulo - codigo de identificação no sistema da biblioteca

codigo_conhecimento - área do conhecimento

autor - nome(s) do(s) autor(es)

curso - curso o qual aquele exemplar se destina

campus - locaização da biblioteca

data_divulgacao - provavelmente ano de aquisição

quantidade_exemplares - número de exemplares

### Carregamento dosDados

In [142]:
df = pd.read_csv('Dados/ifce-biblioteca-livros.csv', sep='\t', encoding='utf-8-sig')

df.head()

,titulo,codigo_titulo,codigo_conhecimento,autor,publicacao,curso,campus,data_divulgacao,quantidade_exemplares
0,A arte da criatividade,140771,NaN,"Judkins, Rod","Rio de Janeiro : Rocco , 2015",NaN,CAMPUS ARACATI,NaN,5
1,!Vale!,33058,.,"Alves, Adda-Nari M.","São Paulo : Moderna , 1997",NaN,CAMPUS IGUATU,20/04/2020,1
2,(A) Teoria da relatividade especial e geral,107280,NaN,"Einstein, Albert","Rio de Janeiro : Contraponto , 1999",Curso Técnico em Eletromecânica Integrado ao E...,CAMPUS TABULEIRO DO NORTE,18/11/2022,1
3,[Uirá dos reis],84019,NaN,NaN,"Fortaleza : Expressão Gráfica , 2009",NaN,CAMPUS ARACATI,NaN,1
4,10 anos com Mafalda,81914,.,Quino,"São Paulo : Martins Fontes , 2011",NaN,CAMPUS CRATO,10/04/2019,1

In [143]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73560 entries, 0 to 73559
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   titulo                 73560 non-null  str
 1   codigo_titulo          73560 non-null  int64
 2   codigo_conhecimento    40870 non-null  str
 3   autor                  60519 non-null  str
 4   publicacao             73373 non-null  str
 5   curso                  23756 non-null  str
 6   campus                 72780 non-null  str
 7   data_divulgacao        28397 non-null  str
 8   quantidade_exemplares  73560 non-null  int64
dtypes: int64(2), str(7)
memory usage: 5.1 MB

In [144]:
df["quantidade_exemplares"].describe()

count    73560.000000
mean         3.879309
std          5.041284
min          0.000000
25%          1.000000
50%          2.000000
75%          5.000000
max         76.000000
Name: quantidade_exemplares, dtype: float64

In [145]:
df.isnull().sum()

titulo                       0
codigo_titulo                0
codigo_conhecimento      32690
autor                    13041
publicacao                 187
curso                    49804
campus                     780
data_divulgacao          45163
quantidade_exemplares        0
dtype: int64

In [146]:
df['codigo_conhecimento'].value_counts()

codigo_conhecimento
.                              35374
Linguística, Letras e Artes      788
Literatura                       608
Literatura Brasileira            440
Ciências Exatas e da Terra       419
                               ...
Agropecuária                       1
Produção Industrial                1
GENERALIDADE                       1
CIENCIAS SOCIAIS EDUCAÇÃO          1
Biodiversidade/Ecologia            1
Name: count, Length: 198, dtype: int64

In [147]:
df_clean = df.drop(['codigo_titulo', 'curso', 'data_divulgacao'], axis=1)

In [148]:
df_clean.head()

,titulo,codigo_conhecimento,autor,publicacao,campus,quantidade_exemplares
0,A arte da criatividade,NaN,"Judkins, Rod","Rio de Janeiro : Rocco , 2015",CAMPUS ARACATI,5
1,!Vale!,.,"Alves, Adda-Nari M.","São Paulo : Moderna , 1997",CAMPUS IGUATU,1
2,(A) Teoria da relatividade especial e geral,NaN,"Einstein, Albert","Rio de Janeiro : Contraponto , 1999",CAMPUS TABULEIRO DO NORTE,1
3,[Uirá dos reis],NaN,NaN,"Fortaleza : Expressão Gráfica , 2009",CAMPUS ARACATI,1
4,10 anos com Mafalda,.,Quino,"São Paulo : Martins Fontes , 2011",CAMPUS CRATO,1

In [149]:
df_clean['quantidade_exemplares'] = df_clean['quantidade_exemplares'].fillna(0).astype(int)

In [150]:
df_clean['codigo_conhecimento'] = df_clean['codigo_conhecimento'].str.replace('.', 'Desconhecido')

In [151]:
df_clean.columns = ["titulo", "area", "autor", "pub", "campus", "exemplares"]

In [152]:
df_clean["campus"] = df_clean["campus"].str.replace("campus ", "", case=False)

In [153]:
df_clean.head()

,titulo,area,autor,pub,campus,exemplares
0,A arte da criatividade,NaN,"Judkins, Rod","Rio de Janeiro : Rocco , 2015",ARACATI,5
1,!Vale!,Desconhecido,"Alves, Adda-Nari M.","São Paulo : Moderna , 1997",IGUATU,1
2,(A) Teoria da relatividade especial e geral,NaN,"Einstein, Albert","Rio de Janeiro : Contraponto , 1999",TABULEIRO DO NORTE,1
3,[Uirá dos reis],NaN,NaN,"Fortaleza : Expressão Gráfica , 2009",ARACATI,1
4,10 anos com Mafalda,Desconhecido,Quino,"São Paulo : Martins Fontes , 2011",CRATO,1

In [154]:
df_clean['campus'].value_counts()

campus
FORTALEZA                            11145
IGUATU                                6808
CRATO                                 6028
LIMOEIRO DO NORTE                     4846
CEDRO                                 3752
MARACANAÚ                             3615
JUAZEIRO DO NORTE                     3130
ARACATI                               2969
CANINDÉ                               2603
SOBRAL                                2548
CRATEÚS                               2232
QUIXADÁ                               2219
ACARAÚ                                1735
CAUCAIA                               1712
TIANGUÁ                               1509
TAUÁ                                  1471
BATURITÉ                              1378
TABULEIRO DO NORTE                    1324
UBAJARA                               1283
ITAPIPOCA                             1191
MORADA NOVA                           1112
LIMOEIRO DO NORTE ( CIDADE ALTA )     1063
JAGUARIBE                              982
HORIZONTE                              953
BOA VIAGEM                             915
CAMOCIM                                633
PARACURU                               578
UMIRIM                                 577
MARANGUAPE                             542
GUARAMIRANGA                           500
ACOPIARA                               444
MEMORIAL DO IFCE                       414
JAGUARUANA                             317
PECÉM                                  192
MOMBAÇA                                 60
Name: count, dtype: int64

In [155]:
df_clean[['origem', 'editora-ano']] = df_clean['pub'].str.split(' : ', n=1, expand=True)

df_clean[['editora', 'ano']] = df_clean['editora-ano'].str.split(' , ', n=1, expand=True)

In [156]:
df_clean.head()

,titulo,area,autor,pub,campus,exemplares,origem,editora-ano,editora,ano
0,A arte da criatividade,NaN,"Judkins, Rod","Rio de Janeiro : Rocco , 2015",ARACATI,5,Rio de Janeiro,"Rocco , 2015",Rocco,2015
1,!Vale!,Desconhecido,"Alves, Adda-Nari M.","São Paulo : Moderna , 1997",IGUATU,1,São Paulo,"Moderna , 1997",Moderna,1997
2,(A) Teoria da relatividade especial e geral,NaN,"Einstein, Albert","Rio de Janeiro : Contraponto , 1999",TABULEIRO DO NORTE,1,Rio de Janeiro,"Contraponto , 1999",Contraponto,1999
3,[Uirá dos reis],NaN,NaN,"Fortaleza : Expressão Gráfica , 2009",ARACATI,1,Fortaleza,"Expressão Gráfica , 2009",Expressão Gráfica,2009
4,10 anos com Mafalda,Desconhecido,Quino,"São Paulo : Martins Fontes , 2011",CRATO,1,São Paulo,"Martins Fontes , 2011",Martins Fontes,2011

In [157]:
df_clean = df_clean.drop(['pub', 'editora-ano'], axis=1)

In [158]:
df_clean.head()

,titulo,area,autor,campus,exemplares,origem,editora,ano
0,A arte da criatividade,NaN,"Judkins, Rod",ARACATI,5,Rio de Janeiro,Rocco,2015
1,!Vale!,Desconhecido,"Alves, Adda-Nari M.",IGUATU,1,São Paulo,Moderna,1997
2,(A) Teoria da relatividade especial e geral,NaN,"Einstein, Albert",TABULEIRO DO NORTE,1,Rio de Janeiro,Contraponto,1999
3,[Uirá dos reis],NaN,NaN,ARACATI,1,Fortaleza,Expressão Gráfica,2009
4,10 anos com Mafalda,Desconhecido,Quino,CRATO,1,São Paulo,Martins Fontes,2011

In [159]:
df_clean[['titulo', 'area', 'autor', 'campus', 'origem', 'editora']] = df_clean[['titulo', 'area', 'autor', 'campus', 'origem', 'editora']].fillna('Desconhecido')

In [160]:
df_clean.head()

,titulo,area,autor,campus,exemplares,origem,editora,ano
0,A arte da criatividade,Desconhecido,"Judkins, Rod",ARACATI,5,Rio de Janeiro,Rocco,2015
1,!Vale!,Desconhecido,"Alves, Adda-Nari M.",IGUATU,1,São Paulo,Moderna,1997
2,(A) Teoria da relatividade especial e geral,Desconhecido,"Einstein, Albert",TABULEIRO DO NORTE,1,Rio de Janeiro,Contraponto,1999
3,[Uirá dos reis],Desconhecido,Desconhecido,ARACATI,1,Fortaleza,Expressão Gráfica,2009
4,10 anos com Mafalda,Desconhecido,Quino,CRATO,1,São Paulo,Martins Fontes,2011

### Etapa de Normalização e Codificação
O objetivo aqui é preprar os dados para a próxima etapa, onde irei completar a coluna de área dos livros usando modelos de classificação, para isso vou me basear em 3 features: titulo, editora e autor, a coluna area será a coluna-alvo.

In [161]:
for coluna in ['titulo', 'area', 'autor', 'editora']:
    df_clean[coluna] = df_clean[coluna].str.lower()

In [162]:
df_clean.head()

,titulo,area,autor,campus,exemplares,origem,editora,ano
0,a arte da criatividade,desconhecido,"judkins, rod",ARACATI,5,Rio de Janeiro,rocco,2015
1,!vale!,desconhecido,"alves, adda-nari m.",IGUATU,1,São Paulo,moderna,1997
2,(a) teoria da relatividade especial e geral,desconhecido,"einstein, albert",TABULEIRO DO NORTE,1,Rio de Janeiro,contraponto,1999
3,[uirá dos reis],desconhecido,desconhecido,ARACATI,1,Fortaleza,expressão gráfica,2009
4,10 anos com mafalda,desconhecido,quino,CRATO,1,São Paulo,martins fontes,2011